apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-test-3
spec:
  replicas: 1
  strategy:
    canary:
      steps:
        - pause: {duration: 30}
        - setWeight: 50
        - pause: {duration: 100}
        - setWeight: 80
        - pause: {duration: 100}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
        - name: guestbook-ui
          image: gcr.io/heptio-images/ks-guestbook-demo:0.2
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: 32Mi
              cpu: 5m
