namePrefix: kustomize-

resources:
  - guestbook-ui-deployment.yaml
  - guestbook-ui-svc.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
images:
  - name: nginx
    newTag: "1.25.1"
  - newTag: 1.25.4
  - newTag: "1.60"
  - newTag: "1.25"
  - newTag: "sdf"
  - newTag: 1254ad
kind: Kustomization