namePrefix: kustomize-

resources:
  - guestbook-ui-deployment.yaml
  - guestbook-ui-svc.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
images:
  - newTag: v5
  - newTag: 1.25.4
  - newTag: "1.25"
  - newTag: "1.25"
  - newTag: "2"
  - newTag: 1254ac
kind: Kustomization