namePrefix: kustomize-

resources:
  - guestbook-ui-deployment.yaml
  - guestbook-ui-svc.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
images:
  - newTag: v5
  - name: nginx
    newTag: 1.25.4
kind: Kustomization